config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_scope :user do
    authenticated :user do
      root :to => 'posts#index', as: :authenticated_root
    end
    unauthenticated :user do
      root :to => "devise/registrations#new", as: :unauthenticated_root
    end
  end

  resources :posts do
    resources :comments
  end
  resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  before_destroy :destroy_comments
  has_many :comments
  belongs_to :user

  private
   def destroy_comments
     self.comments.delete_all   
   end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_many :comments  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_comment, only: [:show, :edit, :update, :destroy]
  before_action :find_post
  def new
    @comment = @post.comments.new
  end

  def create
    @comment = @post.comments.new comment_params
    if @comment.save
      redirect_to @post, notice: "Awesome! You generated comment!"
    else
      render 'new', notice: "Oops, something went wrong! Sorry!"
    end
  end

  def edit
    if current_user.id == @comment.user_id
    else
      flash.now[:alert] = "Error, You are not an owner of this Comment"
      redirect_to @post
    end
  end

  def update
    if @comment.update comment_params
      redirect_to @post, notice: "Your comment was sucessfully updated!"
    else
      render 'edit'
    end
  end

  def destroy
    if current_user.id == @comment.user_id
      @comment.destroy
      redirect_to @post
    else
      flash.now[:alert] = "Error, You are not an owner of this Comment"
      redirect_to @post
    end
  end

  private
    def find_post
       @post = Post.find(params[:post_id])
     rescue ActiveRecord::RecordNotFound
       render "errors/not_found", status: :not_found
    end

    def comment_params
      params.require(:comment).permit(:comment, :post_id).merge(user_id: current_user.id)
    end

    def find_comment
      @comment = Comment.find(params[:id])
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :update, :destroy, :edit]
  before_action :all_comments, only: [:edit, :destroy, :show]
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new post_params

    if @post.save!
      redirect_to @post, notice: "Hey, your post got saved!"
    else
      render "new", notice: "Oooops, something went wrong!"
    end
  end

  def show
  end

  def edit
    if current_user.id == @post.user_id
    else
      flash.now[:alert] = "Error, You are not an owner of this Post"
      render 'show'
    end
  end

  def update
    if @post.update post_params
      redirect_to @post, notice: "Your Post was sucessfully updated!"
    else
      render 'edit'
    end
  end

  def destroy
    if current_user.id == @post.user_id
      @post.destroy
      redirect_to posts_path
    else
      flash.now[:alert] = "Error, You are not an owner of this Post"
      render 'show'
    end
  end  

  private
  def post_params
    params.require(:post).permit(:name, :title, :descripition, :job_type, :level, :location).merge(user_id: current_user.id)
  end

  def find_post
    @post = Post.find(params[:id])
  end

  def all_comments
    @comments = @post.comments
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

 private

 def sign_up_params
   params.require(:user).permit(:name, :email, :password, :password_confirmation, :slack_id)
 end

 def account_update_params
   params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password, :slack_id)
 end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show]
  def show
  end
  private
  def find_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_form.html.erb
<%= form_for [@post, @comment] do |f| %>
  <% if @comment.errors.any? %>
    <h2><%= pluralize(@comment.errors.count, "error") %>Prevented this event from saving:</h2>
    <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <%= f.label :comment %><br>
  <%= f.text_area :comment %><br>

  <br><br>

  <%= f.submit %>
<% end %>

app/views/comments/edit.html.erb
<h2>Edit Comment</h2>

<%= render 'form'%>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form'%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JobFinder</title>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <nav>
     <% if current_user %>
       <p>Hello, <%= current_user.name %>!
       <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
       <%= link_to 'Posts', posts_path %>
       <%= link_to 'Create Post', new_post_path %>
     <% else %>
       <%= link_to 'Register', new_user_registration_path %>
       <%= link_to 'Login', new_user_session_path %>
     <% end %>
    </nav>

    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
    <h2><%= pluralize(@post.errors.count, "error") %>Prevented this post from saving:</h2>
    <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <%= f.label :name, "Company Name" %><br>
  <%= f.text_field :name %><br>

  <br><br>

  <%= f.label :title, "Job Title" %><br>
  <%= f.text_field :title %><br>

  <br><br>

  <%= f.label "descripition" %><br>
  <%= f.text_area :descripition %><br>

  <br><br>

  <%= f.label :job_type %><br>
  <%= f.text_field :job_type %><br>

  <br><br>

  <%= f.label :level %><br>
  <%= f.text_field :level %><br>

  <br><br>

  <%= f.label :location %><br>
  <%= f.text_field :location %><br>

  <br><br>

  <%= f.submit %>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render 'form'%>

app/views/posts/index.html.erb
<div class="container">
  <h2>Posts</h2>
  <table class="hovertable">
    <tr>
      <th>Id</th><th>Title</th><th>Type</th><th>Level</th><th>Company</th><th>Location</th><th>Author</th>
    </tr>
    <% @posts.map do |post| %>
      <tr onmouseover="this.style.backgroundColor='#ffff66';" onmouseout="this.style.backgroundColor='#d4e3e5';">
        <td><%= "#{post.id}" %></td><td><%= link_to "#{post.title}", post_path(post.id) %></td><td><%= "#{post.job_type}" %></td><td><%= "#{post.level}" %></td><td><%= "#{post.name}" %></td><td><%= "#{post.location}" %></td><td><%= link_to "#{post.user.name}", user_path(post.user_id)  %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form'%>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1><br>
<hr>
  <p><%= simple_format @post.descripition %></p>
  <%= link_to "#{@post.user.name}", user_path(@post.user_id)  %>
<hr>

<% @comments.map do |comment| %>
  <%= comment.user.name %>: <%= comment.comment %> <%= link_to "Edit", edit_post_comment_path(post_id: @post.id, id: comment.id) %>, <%= link_to 'Delete',  post_comment_path(post_id: @post.id, id: comment.id),  method: :delete, data: { confirm: 'Are you sure?' } %><br>
<% end %><br>

  <%= link_to 'Edit Post', edit_post_path %>
  <%= link_to 'Delete Post',  post_path,  method: :delete, data: { confirm: 'Are you sure?' } %>
  <%= link_to 'Add Commment', new_post_comment_path(@post.id) %>

app/views/users/show.html.erb
Name: <%= "#{@user.name}" %> <br>
Email: <%= "#{@user.email}" %> <br>
Slack ID: <%= "#{@user.slack_id}" %> <br>